project:
  type: website
  output-dir: docs
  
website:
  title: "R manual"
  sidebar:
    tools:
      - icon: twitter
        href: https://x.com/JordiiSevilla
      - icon: github
        href: https://github.com/SeviJordi
    style: "floating"
    contents:
      - text: "Home"
        href: index.html
      - text: "1. Start"
        href: start.html
      - text: "2. Basics"
        href: basics.html
      - text: "3. I/O"
        href: io.html
      - text: "4. Data management"
        href: data_man.qmd
      - text: "5. Data visualization"
        href: data_viz.html
      - text: "6. Statistics"
        href: stats.html
      - text: "7. Programming"
        href: programming.html
      - text: "8. Final project"
        href: fin_proj.html
 
    
format:
  html:
    self-contained: false
    toc: true
    toc-depth: 4

editor: visual

